services:
  uni-course-management:
    image: ghcr.io/matejstrlek/uni_course_management:latest
    container_name: uni-course-management
    ports:
      - "8081:8081"
    environment:
      MAIL_USERNAME: ${MAIL_USERNAME:-ci-test@example.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-ci-test-password}
      JWT_SECRET: ${JWT_SECRET:-CiTestSecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmOk}
    restart: unless-stopped
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - uni-course-management
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
